name: Documentation Review

on:
  push:
    branches: [main]
    paths:
      - "**.lua"
      - ".github/**"
      - "plugin/**"

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  review-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0 # Fetch full history to analyze changes
          persist-credentials: true

      - name: Run Claude Code to review documentation
        id: claude-review
        uses: anthropics/claude-code-action@8e84799f37d42f24e0ebae41205346879bdcab5a # v0.0.7
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            As a Documentation Validator, review the current code in this repository and ensure that the markdown documentation files (README.md, ARCHITECTURE.md, and DEVELOPMENT.md) are up-to-date and accurate.

            Focus on these specific areas:
            1. Configuration options - Ensure all config options in lua/claudecode/config.lua are accurately reflected in README.md
            2. Commands and usage - Verify all commands and keymaps mentioned in plugin/claudecode.lua are correctly documented in README.md
            3. Architecture details - Validate the module structure in ARCHITECTURE.md matches the actual codebase structure
            4. Development status - Review the implementation status in DEVELOPMENT.md against the actual codebase
            5. Terminal feature - Check that the terminal integration is documented correctly across all files

            If you find any inconsistencies:
            1. Update the documentation files directly with the correct information
            2. Make the changes minimal and focused
            3. Ensure all changes are accurate based on the current codebase

            After making any necessary updates, create a git commit with the message "docs: update documentation to match current codebase" if changes were made.

      - name: Create Pull Request if changes were made
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update documentation to match current codebase"
          title: "docs: Update documentation to match current codebase"
          body: |
            This PR was automatically generated by Claude Code to update documentation files based on code analysis.

            ## What's Changed

            Documentation has been updated to match the current codebase state:
            - Configuration options synchronized with actual code
            - Commands and usage examples verified
            - Architecture details updated to reflect current structure
            - Development status aligned with implementation

            ## Files Updated
            - README.md
            - ARCHITECTURE.md
            - DEVELOPMENT.md

            Please review these changes to ensure they accurately reflect the current state of the project.
          branch: docs/auto-update
          delete-branch: true
